### ISSUE TITLE
google drive链接显示404

### ISSUE THREAD

**Issue by qianye97** [SuperBruceJia/Medical-Concept-Mapping#2]
The pre-trained word vectors can be downloaded [here](https://drive.google.com/file/d/19UoQOS0MCefIiqTqpQAzFePJdsRnmpuC/view?usp=sharing).

The data used for generating the sub-word list can be downloaded [here](https://drive.google.com/drive/folders/189J09QtpoAwrM9YUw1KGMaZSE6g_ukOc?usp=sharing).

哈喽，这两个下载链接显示已失效，可否重新分享一下，不胜感谢！

**Comment by SuperBruceJia** [comment]
Sorry for the late response. I have updated the links.

The pre-trained word vectors can be downloaded [here](https://drive.google.com/file/d/1Rfe7QObJnaOUYK3cIQ6BXLyuJg-5516Y/view?usp=sharing).

The data used for generating the sub-word list can be downloaded [here](https://drive.google.com/drive/folders/19DYs7xQ449DE5QqOQkeGP8fc4Q62iVG7?usp=sharing).

Best regards,

Shuyue
August 5th, 2024
